// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigPath() {
  return window['go']['main']['App']['ConfigPath']();
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function GetAutostart() {
  return window['go']['main']['App']['GetAutostart']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportConfig(arg1, arg2) {
  return window['go']['main']['App']['ImportConfig'](arg1, arg2);
}

export function OpenInFolder(arg1) {
  return window['go']['main']['App']['OpenInFolder'](arg1);
}

export function ParseSSHCommand(arg1) {
  return window['go']['main']['App']['ParseSSHCommand'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function ToSSHCommand(arg1) {
  return window['go']['main']['App']['ToSSHCommand'](arg1);
}

export function ToSSHCommandByID(arg1) {
  return window['go']['main']['App']['ToSSHCommandByID'](arg1);
}

export function TunnelDelete(arg1) {
  return window['go']['main']['App']['TunnelDelete'](arg1);
}

export function TunnelList() {
  return window['go']['main']['App']['TunnelList']();
}

export function TunnelRestart(arg1) {
  return window['go']['main']['App']['TunnelRestart'](arg1);
}

export function TunnelSave(arg1) {
  return window['go']['main']['App']['TunnelSave'](arg1);
}

export function TunnelStart(arg1) {
  return window['go']['main']['App']['TunnelStart'](arg1);
}

export function TunnelStartAll() {
  return window['go']['main']['App']['TunnelStartAll']();
}

export function TunnelStop(arg1) {
  return window['go']['main']['App']['TunnelStop'](arg1);
}

export function TunnelStopAll() {
  return window['go']['main']['App']['TunnelStopAll']();
}
