// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function ConfigPath():Promise<string>;

export function ExportConfig():Promise<string>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetAutostart():Promise<boolean>;

export function GetSettings():Promise<config.Settings>;

export function ImportConfig(arg1:string,arg2:string):Promise<number>;

export function OpenInFolder(arg1:string):Promise<void>;

export function ParseSSHCommand(arg1:string):Promise<config.Tunnel>;

export function QuitApp():Promise<void>;

export function SetSettings(arg1:config.Settings):Promise<void>;

export function TestConnection(arg1:config.Tunnel):Promise<void>;

export function ToSSHCommand(arg1:config.Tunnel):Promise<string>;

export function ToSSHCommandByID(arg1:string):Promise<string>;

export function TunnelDelete(arg1:string):Promise<void>;

export function TunnelList():Promise<Array<config.Tunnel>>;

export function TunnelRestart(arg1:string):Promise<void>;

export function TunnelSave(arg1:config.Tunnel):Promise<config.Tunnel>;

export function TunnelStart(arg1:string):Promise<void>;

export function TunnelStartAll():Promise<void>;

export function TunnelStop(arg1:string):Promise<void>;

export function TunnelStopAll():Promise<void>;
